### ISSUE TITLE
Error while pushing IOC to QRadar

### ISSUE THREAD

**Issue by SkuLLot** [inan19x/misp2qradar#1]
<img width="496" alt="MISP Error" src="https://github.com/inan19x/misp2qradar/assets/143069385/a1662b1b-ba93-4abb-87e9-57bc438d7730">

Got an error message after using misp2qradar_url do you know why this happened

**Comment by inan19x** [comment]
Can you try to change your URL's reference set element type to "Alphanumeric (Ignore Case)" ? For me it works
